### ISSUE TITLE
Add goal to generate jboss-deployment-structure.xml

### ISSUE THREAD

**Issue by jamezp** [wildfly/wildfly-maven-plugin#10]
More of an idea so I don't forget. It could be handy to have add a goal to generate a ```jboss-deployment-structure.xml``` file.

**Comment by jordanglassman** [comment]
+1

**Comment by jamezp** [comment]
Moved to https://issues.jboss.org/browse/WFMP-3

**Comment by kamal-1984** [comment]
+1

**Comment by senyor** [comment]
+1
