### ISSUE TITLE
SAX2 driver class org.apache.xerces.parsers.SAXParser not found

### ISSUE THREAD

**Issue by Tibor17** [wildfly/wildfly-maven-plugin#105]
This goal fails org.wildfly.plugins:wildfly-maven-plugin:1.1.0.Alpha8:execute-commands
because of java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser

This did not happen in Version 1.0.2.

As soon as I remove apache-rat-plugin the issue disappears. The problem is that this plugin checks the license and must be available.

What refactoring change in source code could cause this error in Alpha version?

If I keep the rat-plugin and use Xerces dependency and set a system property, then everything is okay but it is again wrong if I use Maven property instead of system property.
`-Dorg.xml.sax.driver=com.sun.org.apache.xerces.internal.parsers.SAXParser`
```
                    <dependency>
                        <groupId>com.sun.org.apache</groupId>
                        <artifactId>jaxp-ri</artifactId>
                        <version>1.4</version>
                    </dependency>
```

**Comment by Tibor17** [comment]
This is full stack trace

Caused by: java.lang.ExceptionInInitializerError
	at __redirected.__JAXPRedirected.initAll(__JAXPRedirected.java:81)
	at org.wildfly.plugin.cli.ModuleEnvironment.initJaxp(ModuleEnvironment.java:69)
	at org.wildfly.plugin.cli.CommandExecutor.executeCommands(CommandExecutor.java:99)
	at org.wildfly.plugin.cli.CommandExecutor.execute(CommandExecutor.java:73)
	at org.wildfly.plugin.cli.CommandExecutor.execute(CommandExecutor.java:92)
	at org.wildfly.plugin.cli.ExecuteCommandsMojo.execute(ExecuteCommandsMojo.java:91)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 26 more
Caused by: java.lang.RuntimeException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230)
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191)
	at __redirected.__XMLReaderFactory.<clinit>(__XMLReaderFactory.java:66)
	... 33 more
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:82)
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:228)
	... 35 more

**Comment by jamezp** [comment]
There has been quite a bit of refactoring done and more to come. What version of maven are you using? I know nothing in the plugin itself uses xerces.

**Comment by Tibor17** [comment]
Mvn 3.2.1

**Comment by Tibor17** [comment]
I am still using Mvn 3.2.1 with WMP 1.0.2 or Alpha version.
So it should not be Maven related issue.
I think you changed some dependencies did not you?

I know that you do not use Xerces because thus has to do with parsing
```
<execute-commands>
                                <scripts>
                                    <script>
```
and with `ModuleEnvironment.java:69` but I have no idea what this code does or if it is still the same line of code in master.

**Comment by Tibor17** [comment]
Maven should parse the configuration and it should create POJO and inject the object in MOJO field.
Is it this case in your plugin or another kind of parser of executeCommands?

**Comment by jamezp** [comment]
The `ModuleEnvironment` sets up and resets JAXP properties that JBoss Modules sets by default, see https://issues.jboss.org/browse/WFMP-27 for some details there.

I did switch from using WildFly 8 dependencies to WildFly Core dependencies.

I can't seem to duplicate this however. I've tried with Maven 3.2.1, 3.2.5 and 3.3.9. They all seem to work okay for me.

I don't parse anything in the plugin. However the CLI API does attempt to parse a configuration file. I'm just not sure how to duplicate the issue to see what's going on.

**Comment by Tibor17** [comment]
Try to add rat-plugin and exclude everything **/*.* as a workaround that you do not have ASF license in headers.
```
            <plugin>
                <groupId>org.apache.rat</groupId>
                <artifactId>apache-rat-plugin</artifactId>
                <executions>
                    <execution>
                        <id>rat-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <excludes combine.children="append">
                                <exclude>**/README.md</exclude>
                                <exclude>.git/**/*</exclude>
                                <exclude>**/.idea</exclude>
                                <exclude>**/.svn/**/*</exclude>
                                <exclude>src/test/resources/**/*</exclude>
                                <exclude>**/*.jj</exclude>
                                <exclude>src/test/resources/**/*.css</exclude>
                                <exclude>**/*.iml</exclude>
                                <exclude>**/*.ipr</exclude>
                                <exclude>**/*.iws</exclude>
                                <exclude>**/*.tag</exclude>
                                <exclude>**/*.releaseBackup</exclude>
                                <exclude>**/*.versionsBackup</exclude>
                                <exclude>**/*.next</exclude>
                                <exclude>**/release.properties</exclude>
                                <exclude>**/dependency-reduced-pom.xml</exclude>
                                <exclude>**/buildNumber.properties</exclude>
                                <exclude>.mvn/timing.properties</exclude>
                                <exclude>.gitignore</exclude>
                                <exclude>**/META-INF/services/*</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by Tibor17** [comment]
So I made a new try with latest version
`wildfly-maven-plugin:1.1.0.Alpha8:execute-commands`
and I removed all my scripts and added new completely empty script file and the plugin failed with the same stack trace. This means this issue is not related to the content of CLI file.

**Comment by jamezp** [comment]
Okay that got it to fail. I think I see the issue. I'm in the middle of some more refactoring which hopefully I'll be done with soon. I think the issues is the rat plugin initializes the various JAXP factories which use a bunch of static fields so when it attempts to reinitialize them it hits an error because Xerces is no longer on the CP.

I'll have to dig into though to make sure my theory is correct.

**Comment by jamezp** [comment]
Well CLI, really the `org.jboss.as.cli.CommandContext`, is the only thing that should be initializing JBoss Modules. It's definitely the only place that invokes `ModularEnvironment.initJaxp()`.

**Comment by Tibor17** [comment]
@jamezp I have pushed pull-request #106 for this issue.

**Comment by jamezp** [comment]
I'm closing this because I made a [JIRA](https://issues.jboss.org/browse/WFMP-48) issue for it.
