### ISSUE TITLE
Specifying jvm args

### ISSUE THREAD

**Issue by tsundberg** [wildfly/wildfly-maven-plugin#110]
I need to specify a jvm argument. 

It is possible to do using this

`<jvmArgs>-Djboss.management.http.port=${jboss.management.http.port} -Djboss.management.https.port=${jboss.management.https.port}</jvmArgs>`

However, jvmArgs is deprecated. We should use `javaOpts` instead.

Unfortunately, the documentation doesn't descibe how.

A clarifying example in the documentation would be very useful.

**Comment by jamezp** [comment]
Adding documentation is my my TODO list, https://issues.jboss.org/browse/WFMP-43.

Since `javaOpts` is a String array you can just do something like:
```xml
<javaOpts>
    <javaOpt>-Djboss.management.http.port=${jboss.management.http.port}</javaOpt>
    <javaOpt>-Djboss.management.https.port=${jboss.management.https.port}</javaOpt>
</javaOpts>
```

There's an alias on that too so you could use `<java-opts>`/`<java-opt>` instead.

**Comment by jamezp** [comment]
I'm going to go ahead and close this for now as https://issues.jboss.org/browse/WFMP-43 is opened for tracking.
