### ISSUE TITLE
Remote Core with Wildfly running on Docker

### ISSUE THREAD

**Issue by Salaboy** [wildfly/wildfly-maven-plugin#124]
Regarding wildfly-maven-plugin/core/, which contains a README explaining how we can create applications that interact with Wildfly's and EAP servers, but does this work without having access to the jboss/eap home? Is there a way to interact with a remote server (aka running in Docker) by using this lib? I understand that this might use some dependencies to what wildfly already has bundled inside, but we can add those deps to the CP instead. 
Is there any other way (client library) to interact remotly with wildfly 10?

**Comment by jamezp** [comment]
Yes. In fact the only part of the API that needs to know where `JBOSS_HOME` is would be the `ServerProcess` API which you likely wouldn't be using in this case anyway.

The only CP entry you would need is the `jboss-client.jar`  located in the `$JBOSS_HOME/bin/client` directory.
