### ISSUE TITLE
Failed to execute goal on project wildfly-example

### ISSUE THREAD

**Issue by pradeepmallika** [wildfly/wildfly-maven-plugin#126]
While executing the command  ` mvn clean package`  i am getting the below exception....

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.342 s
[INFO] Finished at: 2016-08-12T16:47:58+05:30
[INFO] Final Memory: 9M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wildfly-example: Could not resolve dependencies for project io.katharsis:wildfly-example:war:2.5.0-SNAPSHOT: Could not find artifact io.katharsis:katharsis-rs:jar:2.5.0-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jamezp** [comment]
That error doesn't look like it's coming from the wildfly-maven-plugin. However it's telling you it can't find `io.katharsis:katharsis-rs:jar:2.5.0-SNAPSHOT`. You need to do a `mvn install` on whatever project that is so it will install to your local maven repository.
