### ISSUE TITLE
Plugins is not skipped if goal=undeploy and skip=true

### ISSUE THREAD

**Issue by Tibor17** [wildfly/wildfly-maven-plugin#129]
Plugins is not skipped if goal=undeploy and skip=true.

[INFO] --- wildfly-maven-plugin:1.1.0.Alpha11:undeploy (widfly-shutdown) @ timer-cdi-extension ---
okt 16, 2016 10:51:06 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.1.Final
okt 16, 2016 10:51:06 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.1.Final
okt 16, 2016 10:51:06 PM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 4.0.9.Final

[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.1.0.Alpha11:undeploy (widfly-shutdown) on project timer-cdi-extension: Failed to execute undeploy goal. java.net.ConnectException: WFLYPRT0053: Could not connect to http-remoting://localhost:9990. The connection failed: Connection refused: no further information -> [Help 1]
[ERROR]

**Comment by jamezp** [comment]
Looks like a bug, I've filed a JIRA https://issues.jboss.org/browse/WFMP-68.
