### ISSUE TITLE
Undeploy in domain environment should take domain server-group config into consideration

### ISSUE THREAD

**Issue by askannon** [wildfly/wildfly-maven-plugin#16]
We have an environment were different server groups run artifacts that have very similar names.

E.g. artifact-1.0.0-build3.war runs in group "test" and artifact-1.0.0-build2.war run in group "qanda". Now I want to undeploy the artifact from the "test" group and in the pom there is the following configuration:

```xml
<domain>
  <server-groups>
    <server-group>test</server-group>
  </server-groups>
</domain>
<matchPattern>${project.artifactId}-(\d+\.?){3,}-build\d+.war</matchPattern>
<matchPatternStrategy>fail</matchPatternStrategy>
```

Intiutively I would expect the plugin to match only the artifact deployed into the server group I specified ("test" in this case). But instead I get an error that there are two artifacts deployed, listing also the artifact in the "qanda" group.

It would be great if this behaviour could either be changed to only consider artifacts in the domain groups or - if it needs to be backwards compatible - add another flagg (e.g. "matchServerGroupOnly") with a default to false but at least can enable to only match deployments in a specific server group.

Thanks

**Comment by jamezp** [comment]
Moved to https://issues.jboss.org/browse/WFMP-5
