### ISSUE TITLE
Deploy CLI archive

### ISSUE THREAD

**Issue by saraivinha85** [wildfly/wildfly-maven-plugin#17]
Hello. I'm trying to deploy a CLI zip file using execute-commands.
This is my command:

<commands>
         <command>deploy ${basedir}/target/install-postgresql-driver.cli</command>
 </commands>                                

Using this command directly on JBOSS CLI works, but using the maven plugin shows the following error:

Set 18, 2014 9:29:35 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.2.2.Final
Set 18, 2014 9:29:35 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.2.2.Final
Set 18, 2014 9:29:35 AM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 4.0.3.Final
WARN: can't find jboss-cli.xml. Using default configuration values.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.394s
[INFO] Finished at: Thu Sep 18 09:29:35 WEST 2014
[INFO] Final Memory: 36M/979M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.0.3.Final-SNAPSHOT:execute-commands (Install) on project oobian-installer: Execution Install of goal org.wildfly.plugins:wildfly-maven-plugin:1.0.3.Final-SNAPSHOT:execute-commands failed: Command 'deploy /installer/target/install-postgresql-driver.cli' is invalid. JBOSS_HOME environment variable is not set. -> [Help 1]

**Comment by jamezp** [comment]
If this is still an issue please file a new issue at https://issues.jboss.org/browse/WFMP.
