### ISSUE TITLE
Unable to "run" while also deploying-artifact and deploying application

### ISSUE THREAD

**Issue by codylerum** [wildfly/wildfly-maven-plugin#2]
I'm trying to setup a deployment for a benchmark.

What needs to happen is a server needs to be downloaded, started, database driver deployed, datasource deployed, application deployed. It has to happen in that order or the application will fail to deploy.

The command I'm trying to run is 

`mvn wildfly:run -Dwildfly.version=8.0.0.CR1`

However the problem is that with my deploy-artifact and add-resource executions are in phase package and package is executed before the run...so before the server starts and thus they fail.

if I set them to deploy they never run.

`mvn wildfly:start wildfly:deploy -Dwildfly.version=8.0.0.CR1` gives me a successful deployment but the server shuts down as soon as it is deployed. I need it to keep running for the benchmark.

Is this possible? It's like I need an after server started phase or  package needs to be executed after mvn:run not before.

https://github.com/codylerum/FrameworkBenchmarks/blob/wildfly/wildfly/pom.xml

**Comment by jamezp** [comment]
Cleaning up issues, please re-open if you feel this is still an issue.
