### ISSUE TITLE
wildfly:run fails when CLI command :reload is executed

### ISSUE THREAD

**Issue by acdcjunior** [wildfly/wildfly-maven-plugin#21]
To reproduce:

- Create an empty project, containing only this `pom.xml` at the root:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation=
                "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <artifactId>wildfly-maven-reload</artifactId>
    <groupId>wildfly-maven-reload</groupId>
    <version>0.0.1</version>
    <packaging>war</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <version>1.0.2.Final</version>
                <configuration>
                    <beforeDeployment>
                        <commands>
                            <command>:reload</command>
                        </commands>
                    </beforeDeployment>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

- And this (empty) `web.xml` in `\src\main\webapp\WEB-INF`:

```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation=
           "http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
      version="3.0"> 
  
</web-app>
```

- Then run `mvn clean wildfly:run` (the `clean` is obviously optional).

It all works fine until it executes the `:reload`, then the plugin seems to lose the connection, yielding the following error:

> `[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.0.2.Final:run (default-cli) on project wildfly-maven-reload: The server failed to start: Command execution failed for command ':reload'. Communication error: java.util.concurrent.ExecutionException: Operation failed: Channel closed -> [Help 1]`

Needless to say, without the `:reload` there, it works (even with other CLI commands, though most of them have limited use, due to depending on reloading).

**Comment by jamezp** [comment]
Moved to https://issues.jboss.org/browse/WFMP-6
