### ISSUE TITLE
[Question/Request] Can the Shutdown goal, support by configuration the restart=true option

### ISSUE THREAD

**Issue by javapapo** [wildfly/wildfly-maven-plugin#24]
Hi, my main goal is to deploy apps on wildfly but restart at some point my local or remote server (prior or after the deployments). 

The current wildfly maven plugin, provides a shutdown goal, but comparing with the CLI equivalent which you can issue :shutdown(restart=true) , I can not define restart =true on the maven goal.

So in order to do my restart, using the plugin I have been using the execute-commands goal
```xml
   <execution>
                                <id>RESTART WILDFLY</id>
                                <phase>install</phase>
                                <configuration>
                                    <execute-commands>
                                        <commands>
                                            <command>:shutdown(restart=true)</command>
                                        </commands>
                                    </execute-commands>
                                </configuration>
                                <goals>
                                    <goal>execute-commands</goal>
                                </goals>
                  </execution>
```

The problem is that for some reason (probably in the plugin implementation) right after the command invocation, the server restarts and the plugin immediately reports that it can not get a feedback from the running server,

**Comment by jamezp** [comment]
Moved to https://issues.jboss.org/browse/WFMP-7
