### ISSUE TITLE
[question/issue] Maven classifier

### ISSUE THREAD

**Issue by fredmobilinn** [wildfly/wildfly-maven-plugin#25]
Hello,
I want to deploy a war with a pom.xml defining multiples maven profile.
In each profile, in the build section, I have configure the maven war pluggin to use a classifier. When I build my war with a classifier the generated binarie is subfixed with a classifier : for exemple mywar-production.war (with a 'production' classifier. When I run the wildfly:deploy goal the pluggin wants to deploy the mywar.war binarie not mywar-production.binarie. Have you got a solution ?

Thank you,

Fred

**Comment by jamezp** [comment]
Have you tried using the `<filename/>` configuration element?

**Comment by fredmobilinn** [comment]
Yes it works ! You then need to explicitly specify the filename like ${artifactid}-myclassifier.war for exemple. I think that this would be more homogeneous  if there was a classifier attribute like others maven pluggins. This is just an enhancement and the filename works as well. Thank you !
