### ISSUE TITLE
The plugin cannot skip start and shutdown

### ISSUE THREAD

**Issue by tsegismont** [wildfly/wildfly-maven-plugin#26]
In RHQ and the Hawkular metrics projects, we use the Wildfly Maven plugin to start a server and deploy an application for integration testing.

To sum up, we attach the following goals to different build phases:
* pre-integration-test -> start
* pre-integration-test -> deploy
* post-integration-test -> shutdown

The deploy goal has a skip parameter:
https://docs.jboss.org/wildfly/plugins/maven/latest/deploy-mojo.html#skip

But the start and shutdown goals haven't. So when we disable tests, we can skip the deploy phase but Maven will still start and stop the Wildfly server.

**Comment by tsegismont** [comment]
I've tested a local build of the plugin with the changes.

On the Hawkular metrics rest-tests module, build time goes from 15 seconds down to 5 seconds when start and stop goal are skipped.

**Comment by isavin** [comment]
@jamezp would it be possible to release a new version of the plugin with this fix included? Thanks!

**Comment by jamezp** [comment]
I'm a bit late, but I released a 1.1.0.Alpha1 version.

**Comment by isavin** [comment]
Perfect. Thank you!

**Comment by tsegismont** [comment]
Thanks!
