### ISSUE TITLE
wildfly:run fails to run the Wildfly

### ISSUE THREAD

**Issue by harishkannarao** [wildfly/wildfly-maven-plugin#33]
Hi Team,
To reproduce this issue:
Create an empty project, containing only this pom.xml at the root:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>maven.wildfly</groupId>
    <artifactId>maven-wildfly</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <build>
        <plugins>
            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-maven-plugin</artifactId>
                <version>1.1.0.Alpha1</version>
            </plugin>
        </plugins>
    </build>
</project>

The contents of pom.xml is not displayed properly, hence I have attached an image of pom.xml
And run: mvn wildfly:run -Dwildfly.version=8.2.0.Final

Then the following error is generated:
 Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.1.0.Alpha1:run (default-cli) on project maven-cargo-wildfly: The deployment 'MavenCargoWildfly\target\maven-wildfly-1.0-SNAPSHOT.maven-project' could not be found. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

However start goal works fine:
For e.g: mvn wildfly:start -Dwildfly.version=8.2.0.Final

**Comment by harishkannarao** [comment]
![pom](https://cloud.githubusercontent.com/assets/3831063/6573094/78f67b26-c70f-11e4-9eb4-e58f90906283.png)

**Comment by jamezp** [comment]
The start goal attempts to start and deploy an application. Since your pom has a packing type of `pom` it attempts to deploy `maven-wildfly-1.0-SNAPSHOT.maven-project` which does not exist. I assume you have a WAR or EAR module on here. You need to use the following configuration.

```xml
<plugin>
    <groupId>org.wildfly.plugins</groupId>
    <artifactId>wildfly-maven-plugin</artifactId>
    <version>1.1.0.Alpha1</version>
    <configuration>
        <skip>true</skip>
    </configuration>
</plugin>
````

Then in either your EAR or WAR project use the same configuration except change the `<skip>true</skip>` to `<skip>false</skip>`.

**Comment by harishkannarao** [comment]
Hi Team,

Thanks for the response.
With the packaging type as 'pom', start goal is able to run successfully.
Its only the run goal fails.

With packaging type as 'pom', when I run "mvn wildfly:start", it runs successfully, where as "mvn wildfly:run" fails.

Our use case is, The plugin will be used in a parent pom of QA functional and integration tests, which will start an existing wildfly instance in local machine without deploying any app.  The setup of wildfly with the deployments and configuration is already done by a script.  We only need to start the existing local wildfly with the existing configurations (standalone.xml, ears, etc).  So we need to use this plugin in a pom, which has packaging type as 'pom', as we don't have anything to deploy in our use case.

If the wildfly:run goal, gracefully ignores the deployment if the packaging type is 'pom' then it will be very helpful for us.  You can take this as a feature request to this plugin.

**Comment by jamezp** [comment]
It doesn't sound like you want the `run` goal anyway. That goal will deploy an application and block until you shutdown WildFly or use `SIGINT` for the process.

**Comment by harishkannarao** [comment]
The use case is, "start" goal will be used while running "mvn clean install".  If there are any test failures, then "mvn wildfly:run" will be executed and the individual failing test will be run from IDE to debug or to fix the test.  The idea was to use the "run" goal similar to starting a wildfly from bin folder and stop it whenever the debugging is completed, but the maven configurations will abstract the actual details to be made in the wildfly server startup by using standalone.bat or standalone.sh (for e.g sending server args for port offset, setting jvm args etc will be captured in the pom.xml) instead of setting it through standalone.conf.bat or command line

**Comment by jamezp** [comment]
It would probably be best to set a profile which can be run on the specific deployment then. Note though that maven will block though and no further plugins, goals or anything from maven will be executed.

As an example in your WAR you could do something like:
```xml
    <profiles>
        <profile>
            <id>test.debug</id>
            <activation>
                <property>
                    <name>test.debug</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.wildfly.plugins</groupId>
                        <artifactId>wildfly-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals>
                                    <goal>run</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
```

You can then just do `mvn package -Dtest.debug` or `mvn package -Ptest.debug`.

**Comment by harishkannarao** [comment]
\<?xml version="1.0" encoding="UTF-8"?\>
\<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"\>
    \<modelVersion\>4.0.0\</modelVersion\>
    \<groupId\>maven.wildfly\</groupId\>
    \<artifactId\>maven-wildfly\</artifactId\>
    \<version\>1.0-SNAPSHOT\</version\>
    \<packaging\>pom\</packaging\>
    \<build\>
        \<pluginManagement\>
          \<plugins\>
              \<plugin\>
                  \<groupId\>org.wildfly.plugins\</groupId\>
                  \<artifactId\>wildfly-maven-plugin\</artifactId\>
                  \<version\>1.1.0.Alpha1\</version\>
              \</plugin\>
          \</plugins\>
        \</pluginManagement\>
    \</build\>
    \<profiles\>
      \<profile\>
            \<id\>test.run\</id\>
            \<activation\>
                \<property\>
                    \<name\>test.run\</name\>
                \</property\>
            \</activation\>
            \<build\>
                \<plugins\>
                    \<plugin\>
                        \<groupId\>org.wildfly.plugins\</groupId\>
                        \<artifactId\>wildfly-maven-plugin\</artifactId\>
                        \<executions\>
                            \<execution\>
                                \<phase\>pre-integration-test\</phase\>
                                \<goals\>
                                    \<goal\>run\</goal\>
                                \</goals\>
                            \</execution\>
                        \</executions\>
                    \</plugin\>
                \</plugins\>
            \</build\>
        \</profile\>
        \<profile\>
              \<id\>test.start\</id\>
              \<activation\>
                  \<property\>
                      \<name\>test.start\</name\>
                  \</property\>
              \</activation\>
              \<build\>
                  \<plugins\>
                      \<plugin\>
                          \<groupId\>org.wildfly.plugins\</groupId\>
                          \<artifactId\>wildfly-maven-plugin\</artifactId\>
                          \<executions\>
                              \<execution\>
                                  \<phase\>pre-integration-test\</phase\>
                                  \<goals\>
                                      \<goal\>start\</goal\>
                                  \</goals\>
                              \</execution\>
                          \</executions\>
                      \</plugin\>
                  \</plugins\>
              \</build\>
          \</profile\>
    \</profiles\>
\</project\>

**Comment by harishkannarao** [comment]
Hi James,

I had tried the following commands with the above pom.xml.  Please note the packaging type is still 'pom':
mvn clean install -Dtest.start
mvn clean install -Dtest.run

"mvn clean install -Dtest.start" works even if the packaging type is 'pom', it doesn't try to deploy the current module if the packaging type is 'pom'.  However "mvn clean install -Dtest.run" doesn't work, because it tries to deploy the current module with packaging as 'pom'.

It will be ideal if the "run" goal gracefully ignores the deployment step if the packaging type of the module is 'pom' and just carry on in starting the wildfly server.

Regards,
Harish

**Comment by harishkannarao** [comment]
Hi Team,

I had a look at org.wildfly.plugin.server.RunMojo.java file.
The doExecute() method checks for the deploymentFile, whether it exists or not.
If the doExecute() checks if the package type is not ignored (org.wildfly.plugin.deployment.PackageType.isIgnored) and then deploy the package if the package type is not ignored.
I can see isIgnored() method is always returning false, but I guess it will be enhanced to return 'true' if the package type is 'pom'

**Comment by jamezp** [comment]
Ignoring the package type wouldn't really work. Say you have an EAR project. That EAR likely depends on a WAR and maybe an EJB jar. If we skipped the POM and the EJB jar would likely build first and then that would where the run goals is executed. The run goal needs to be run on the sub-module that you'd like to run. There's no way around that.

**Comment by harishkannarao** [comment]
Hi James,

My use case is:
As a developer, I want to start an existing local wildfly instance before running integration test and shutdown the instance once the integration test is completed.  This use case is satisfied by "wildfly:start" goal.  This goal is a non-blocking goal and hence carries on to run the integration tests.  This goal works even with packaging type as 'pom'

My other user case is:
As a developer, I want to start an existing local wildfly instance and keep running this instance until I press ctrl+c.  This will enable me to verify my application manually and also helps me to run single integration test from IDE.  I couldn't use the start goal because it doesn't keep the server running.  Also I couldn't use run goal because it tries to deploy the module and fails if the module is of packaging type 'pom'.  I want a goal similar to 'start', which will keep the server running, but doesn't try to deploy like the 'run' goal.

Do we have any mechanism to achieve this?  If not available, then can it be taken up as a request for enhancement?

**Comment by harishkannarao** [comment]
Also, in my previous comment, I was not suggesting to ignore the whole module if the packaging is 'pom'.  What I was suggesting was:
In the code, as part of RunMojo, there is a check to see if the deployment file exists and this deployment file is deployed to the running instance of wildfly.  I was suggesting if the check is removed if the packaging type is 'pom' and subsequently by-pass the deployment step alone if the packaging type is 'pom', otherwise it will continue to perform as it does now..It can move on to its sub-modules and continue to do it recursively.

**Comment by harishkannarao** [comment]
Also when I was referring to the documentation for "run" goal as in here..
https://docs.jboss.org/wildfly/plugins/maven/latest/run-mojo.html

The property "checkPackaging" describes something like maven package types 'pom' is ignored.

**Comment by jamezp** [comment]
There are two ways this will work.

1. You could `cd` into the maven module you want to run, e.g. your war module, and execute `mvn wildfly:run`.
2. You could create a profile for the `run` goal in the module pom for your deployment.

That's the only way it can work. There's no way for the plugin to know which child of the parent should be run.

**Comment by harishkannarao** [comment]
Hi James,

I don't have a war module in my project.  It is only root model and two sub modules which are acceptance test modules.. The war will be available in the internal maven repository uploaded by the development team.  This use case is for the QAs to download the war file from internal maven repository and deploy in the local wildfly instance and start the instance before running the acceptance test.  The above method will work for the development team, who generates the war.  But our use case is QA acceptance test is in different repository, which doesn't contain the war module, it contains only the acceptance tests.

**Comment by jamezp** [comment]
The `run` goal is meant to deploy the maven artifact it is working with. I'd consider changing the `start` goal to not exit after the maven build is complete. There's no changes for the `run` goal that would work for what you're trying. It's mean to run WildFly, deploy an archive and block until `SIGINT` is hit.

**Comment by harishkannarao** [comment]
Yes, if the start goal takes an extra flag or variable and keeps the wildfly to run until ctrl+c is pressed will be ideal for me..

**Comment by jamezp** [comment]
It can't block until `CTRL`+`C` is pressed. There's no way for the process to know where to block.

**Comment by harishkannarao** [comment]
Hi, in your previous comment you suggested to consider changing the start goal not to exit after the build is complete.  I want that feature.  If the start goal doesn't exit after build, then there should be some mechanism to stop it once the user want to stop it

**Comment by jamezp** [comment]
The only way would be to issue a shutdown to the server process or kill the processes. You can do this via the `shutdown` goal, executing `$JBOSS_HOME/bin/jboss-cli.sh -c ":shutdown"` or any other management way of shutting it down.

**Comment by harishkannarao** [comment]
That will solve our use case.  I can use shutdown goal to stop the running instance.  So my understanding is "start" goal will take some flag to leave the server running even after the maven build is complete and then I can use "shutdown" goal to stop the running instance.  This will work perfectly for my use case.  Please take this as a change request or enhancement.

**Comment by jamezp** [comment]
Closing in favor of #34
