### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by gtstewart** [wildfly/wildfly-maven-plugin#37]
I think it would be a help to new user if the documentation for the plugin at https://docs.jboss.org/wildfly/plugins/maven/latest/index.html included examples where the server was hosted on another machine other than the localhost or provided a list of the properties that can be set.

I know it took me several hours of research to find what settings where required to deploy my application using the plugin to a wildfly instance on another machine on the network. By default the plugin will always look for an instance on 127.0.0.1:9990.

Graham

**Comment by jamezp** [comment]
The documentation on the goals is pretty clear what the defaults are. Have a look at [hostname](https://docs.jboss.org/wildfly/plugins/maven/latest/deploy-mojo.html#hostname) property and the [port](https://docs.jboss.org/wildfly/plugins/maven/latest/deploy-mojo.html#port) property.

Of course contributions on documentation are always welcome :)
