### ISSUE TITLE
Allow deployments from remote hosts/repositories

### ISSUE THREAD

**Issue by smoyer64** [wildfly/wildfly-maven-plugin#49]
Changing targetDir in AbstractAppDeployment from File to URL would allow both local and remote files to be deployed.  The default targetDir value works perfectly for our non-production systems, but for our production servers we'd rather install and deploy our WAR files to our artifact repository, and then deploy the WAR file from artifact repository.

**Comment by smoyer64** [comment]
@jamezp - If you think this is a good idea, you can assign it to me.  I also want to fix an issue with the security I added in jboss-as-maven-plugin 7.4.Final.

**Comment by jamezp** [comment]
Let me think on this. My initial reaction is this is out of the scope for the plugin. Mainly because it's intention is to be used during the build process.

**Comment by smoyer64** [comment]
I can argue for and against my case ... let me know what you decide.

**Comment by jamezp** [comment]
Absolutely :) Let's discuss it here though https://issues.jboss.org/browse/WFMP-9.

**Comment by Scuilion** [comment]
If this is "out of scope" for this plugin, is there an alternative for deploying remote sources?

**Comment by jamezp** [comment]
There's not at this point that I know of. The idea hasn't been rejected yet :) I'm just apparently slow at making decisions. My gut tells me there's some security concerns with using URL vs File.
