### ISSUE TITLE
start wildfly in background?

### ISSUE THREAD

**Issue by The-Alchemist** [wildfly/wildfly-maven-plugin#50]
I'm wondering if there's a way to start WF in the background for the ```wildfly:start``` goal, skin to the ```<daemon>true</daemon>``` option used for just this purpose with the maven jetty plugin.

Basically, I have some Java tests I'd like to run using the maven-failsafe-plugin after starting WF.

Thanks!

**Comment by jamezp** [comment]
Please see https://issues.jboss.org/browse/WFMP-1
