### ISSUE TITLE
Support for runtime-name/commonName

### ISSUE THREAD

**Issue by voidswitch** [wildfly/wildfly-maven-plugin#52]
In domain-mode sometimes the same application needs to be deployed in different versions on multiple server-groups. If deployed by hand this can be achieved by setting a different name, but common runtime-name. 

The wildfly DeploymentPlanBuilder supports setting name and commonName, which can be used in DomainDeployment. I've implemented parts of it. As I haven't any knowledge of Maven plugin development, I don't know what more has to be done to make this work. 

see voidswitch/wildfly-maven-plugin@bf37175d4ad401798030fb00cd70968a80cb247f

**Comment by sventorben** [comment]
A collegue of mine just came along with the same issue. Unfortunately, I overlooked your post here and implemented something nearly identical.
Have a look at sventorben/wildfly-maven-plugin@d81ef9395c99f4fd7271f4d68fa37b73a28a599f

**Comment by The-Alchemist** [comment]
Any chance of these being merged?: )

**Comment by jamezp** [comment]
See https://issues.jboss.org/browse/WFMP-16. I'll have a new PR up in a bit since the previous one needs some rebasing. Just testing it now.
