### ISSUE TITLE
executeCommands does not respect jbossHome configuration

### ISSUE THREAD

**Issue by freiser77** [wildfly/wildfly-maven-plugin#61]
When you create a module with the following command, you will receive an error, that JBOSS_HOME is not set. In the configuration of the wildfly-maven-plugin however the jbossHome value is set.

    module add --name=org.hsqldb --dependencies=javax.api,javax.transaction.api --resources=${hsqldb.jar.path}

In my opinion the error is in ASModuleHandler:412

     final String modulesDirStr = WildFlySecurityManager.getEnvPropertyPrivileged(JBOSS_HOME, null);

**Comment by jamezp** [comment]
This is fixed in WildFly Core 2 https://github.com/wildfly/wildfly-core/blob/master/cli/src/main/java/org/jboss/as/cli/handlers/module/ASModuleHandler.java#L414-L418.

In version 1.1.0.Alpha3 of the wildfly-maven-plugin setting the `jbossHome` will launch a new process so the `JBOSS_HOME` environment variable should be set. https://github.com/wildfly/wildfly-maven-plugin/pull/59

**Comment by freiser77** [comment]
Even with this execution configuration the jbossHome property is not set. So the new process is never launched.

         <execution>
                                <id>setup-env</id>
                                <phase>package</phase>
                                <goals>
                                    <goal>execute-commands</goal>
                                </goals>
                                <configuration>
                                    <executeCommands>
                                        <scripts>
                                            <script>
                                                ${build.directory}/filtered-wildfly-config/scripts/installHsqldb.cli
                                            </script>
                                            <script>
                                                ${build.directory}/filtered-wildfly-config/createDbConnections.cli
                                            </script>
                                        </scripts>
                                    </executeCommands>
                                    <jbossHome>${profile.jbossHome}</jbossHome>
                                </configuration>
                            </execution>

**Comment by freiser77** [comment]
Upgrade to version 1.1.0.Alpha3 and usage of wildfly-core 2 fixed the issue
