### ISSUE TITLE
Prevent build failure when execute-command fails

### ISSUE THREAD

**Issue by thbono** [wildfly/wildfly-maven-plugin#62]
When running a build with an execute-commands goal that fails, the entire build fails itself. 

Is there a way to prevent/avoid this?

**Comment by sventorben** [comment]
Take a Look at #47

**Comment by jamezp** [comment]
Closing in favor of this JIRA https://github.com/wildfly/wildfly-maven-plugin/issues/62. There seems to be a lot of requests for this so I guess I better let it happen :)
