### ISSUE TITLE
Unable to connect for deployment when port is specified by a user property

### ISSUE THREAD

**Issue by cpupower** [wildfly/wildfly-maven-plugin#65]
In wildfly-maven-plugin version **1.0.2.Final** and **1.1.0.Alpha3** (other versions not tested) when changing the wildfly port via the user property "**wildfly.port**", the connection fails with a "**connection timed out**" message. When connecting via netcat to the same port, the HTTP server responds normally.
When not specifying a port, the default port 9990 is used and the connection succeeds (if the server is running under the default port).

Command:
> mvn wildfly:deploy -Dwildfly.port=9999

Error message:
> [ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:1.0.2.Final:deploy (default-cli) on project <projectName>: Could not execute goal deploy on <fullpathToWar>. Reason: I/O Error could not execute operation '{
> [ERROR] "operation" => "read-attribute",
> [ERROR] "address" => [],
> [ERROR] "name" => "launch-type"
> [ERROR] }': java.net.ConnectException: JBAS012144: Could not connect to remote://127.0.0.1:9999. The connection timed out

**Comment by jamezp** [comment]
The factory used to connect will try the `remoting`protocol if the port is `9999` for legacy reason. Try overriding the protocol `-Dwildfly.protocol=http-remoting` or `<protocol>http-remoting</protocol>`.

**Comment by cpupower** [comment]
Thank you, that solved the problem!
