### ISSUE TITLE
Run command before deployment not in batch mode

### ISSUE THREAD

**Issue by blackat** [wildfly/wildfly-maven-plugin#67]
Hi,
I am using the Alpha 4 and I would like to run some commands before the deployment when I run `wildfly:run` so I specify

```xml
    <beforeDeployment>
        <commands>
            <batch>false</batch>
            <command>
                run-batch --file=foo.cli
            </command>
        </commands>
    </beforeDeployment>
```
as far as I have understood the batch mode is enabled by default, I would like to run some commands frm a script file such as `run-batch --file=foo.cli` but I should not be in _batch mode_.

When I run I got the following issue
`Unexpected command 'false'. Type 'help --commands' for the list of supported commands.`

From the source code and the doc of `org.wildfly.plugin.cli.Commands` of I expect that I can disable the _batch mode_ in this way

```xml
<commands>
    <batch>false</batch>
    <command>
        /subsystem=logging/console-handler:CONSOLE:write-   attribute(name=level,value=TRACE)
    </command>
</commands>
```

Differently when I run
```xml
    <beforeDeployment>
        <batch>false</batch>
        <commands>
            <command>
                run-batch --file=foo.cli
            </command>
        </commands>
    </beforeDeployment>
```
this seems working so is there an issue with the documentation?

Moreover the option `<batch>false</batch>` is not documented under `<beforeDeployment>` could you please add it?

P.S. I understand the plugin is still in Alpha so I try to contribute a bit :-)

**Comment by jamezp** [comment]
The `run-batch` command isn't valid in the context you're trying to run it on. If you're trying to run a script file look at the example for executing commands, https://docs.jboss.org/wildfly/plugins/maven/latest/examples/execute-commands-example.html#Execute_commands_from_CLI_scripts.

The `<beforeDeployment>` is exactly like the `execute-commands` examples except you'd replace `<execute-commands>` with either `<before-deployment>` or `<after-deployment>`.

**Comment by blackat** [comment]
I have seen from the source code I can use `<scripts>`, it was not documented but it has solve my issue now.

And the tag `<batch>` is it valid in the context? 

My understanding was that by default it is true, so when the execution enters in `<commands>` it is like having run in the cli `batch`, instead with `<batch>false</batch>` it should be in `batch mode` and the command ``run-batch --file=foo.cli` could have been run.

Thanks

**Comment by jamezp** [comment]
No. The `<batch>true</batch>` just wraps the CLI commands in `batch` and `run-batch`. In hindsight it wasn't really needed and should be maybe be deprecated. It's set to `false` by default as that's the default for booleans.

**Comment by blackat** [comment]
I thought the default value was `true` because when I run `run-batch --file=foo.cli` I get the error telling me the `run-batch` cannot be run when in `batch mode` so I have tried to put `<batch>false</batch>` and I got another issue.

About the deprecation of the `<batch>` I am  not sure, but it would be good if I can do as the documentation of the CLI shows the use of `batch`

- `batch` and then `run-batch` (automatically executed by the plugin)
- execute a `run-batch --file=foo.cli` so the `batch mode` disabled

Thanks again for the time and attention :wink:

**Comment by jamezp** [comment]
This worked for me leaving off the `<batch/>` property. Though I'd still suggest using the `<scripts><script/></scripts>`.
