### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by blackat** [wildfly/wildfly-maven-plugin#68]
Hi,
I see there are some properties not documented such as

```xml
<beforeDeployment>
    <scripts>
        <script>
            foo.cli
        </script>
    </scripts>
</beforeDeployment>
```
I can run a script file for instance, but this optional parameter is not present in the documentation, could you please update the documentation?

Thanks a lot for you attention.

P.S. I understand the plugin is still in Alpha so I try to contribute a bit :-)

**Comment by jamezp** [comment]
Sorry for the long delay, but this is documented in the execute-commands example file:///home/jperkins/projects/jboss/wildfly/wildfly-maven-plugin/plugin/target/site/examples/execute-commands-example.html.
