### ISSUE TITLE
Undeploy war when shutdown

### ISSUE THREAD

**Issue by blackat** [wildfly/wildfly-maven-plugin#71]
Hi,
I am using the goal `wildfly:run` to deploy and start an application, is there a way to undeploy the war application during the shutdown of the server?

I have a huge war application so once it has been deployed the first time is fine, but when I run again the command `mvn wildfly:run` the server starts along with the application, then a new packed war of the same application is redeployed and started. Everything works correctly but it takes a quite good amount of time.

Any solution is appreciated ;-)

**Comment by jamezp** [comment]
The `run` goal is meant for development and managing a server. I don't see a reason to skip a deployment operation from this goal when it's run. If you don't want it redeployed it's best to not use the `run` goal and deploy it once to a running instance of WildFly.

**Comment by blackat** [comment]
May be I can explain my scenario during the __development__:
- I do some modification to code I want to test
- I run `wildfly:run` so the `war` is generated and deployed
- I stop via `Ctrl + c` or a button if I am in Intellij Idea
- I do some other modifications and I run again `wildfly:run`
- A new `war` file is generated, the server starts along with the old application, then the new `war` is deployed.

the problem is that we have a huge war and it takes a while for the deployment phase, so it would be good for instance having the opportunity to undeploy during the shutdown so next time when the server starts again the new artifact can be deployed immediately without waiting too much time.

I hope I have better explained our scenario.

**Comment by jamesnetherton** [comment]
So why not manage and start your own WildFly instance which you leave running.

Then you can use the plugin to redeploy every time you make changes to your application with `mvn wildlfy:deploy`.

Also, if you're using IntelliJ. You can [deploy applications to WildFly from the IDE](https://www.jetbrains.com/idea/help/application-servers.html).

**Comment by blackat** [comment]
Basically the idea is to replace the Jetty plugin and having something more or less similar, we are in an heterogeneous environment with different backgrounds and I try to minimize the deployment step.

About the plugin I guess you have checked that is for the __Ultimate version__, so not all of us have that version and we have to keep using Idea.

On my side I use the ultimate and that plugin does the undeploy during the shutdown, for me it is fine but I need to provide something even for other people.
I do not want to explain all the details because I guess it is out of scope.

**Comment by jamezp** [comment]
You could do `mvn clean wildfly:run` which would give you a clean instance of WildFly. As far as undeploying there's no real good way to do that. Using `CTRL+C` kills the process which means there's not place where an undeploy could be run.

**Comment by blackat** [comment]
I agree but I think your command works well when you do not specify an already installed instance of WildFly, in my case I specify a JbossHome so the `mvn clean` I think does not affect the server.

I understand the point about `CTRL+C`, may be it is possible to do something at beginning, just say may be because I do not know the WildFly source code, thus by a specific boolean tag I can specify if the already deploy application named `${project.build.fileName}` should be undeployed or removed before redeploying it.

It is just an idea for an improvement, I guess other people could get into the same situation, I do not know if it is feasible according to the API you deal with.

In any case thanks a lot for your help, it is really appreciated :wink:
