### ISSUE TITLE
wildfly:execute-commands should support embed-server mode

### ISSUE THREAD

**Issue by bakito** [wildfly/wildfly-maven-plugin#72]
Since Wildfly 9 cli supports embed-server mode.
http://wildfly.org/news/2015/03/13/Offline-CLI/

The plugin should support this, without connecting to the manager port

**Comment by jamezp** [comment]
What would the use case be?

**Comment by bakito** [comment]
The use case to prepare a wildfly configuration within a maven build. The configuration should be build in an offline environment. I do not have the possibility to start a wildfly that opens any ports.

As also described in the article i mentioned above: 'The immediate goal is to support direct local administration of a WildFly installation via the CLI without requiring a socket-based connection. The general use case is initial setup type activities where the user doesn’t want to have to launch a WildFly server and have it be visible on the network.'

**Comment by jamezp** [comment]
I'd have to give this some thought. My initial thought is having the maven plugin essentially handle provisioning seems a bit out of scope. I'd almost rather see a different plugin for it.

**Comment by ssaarinen** [comment]
I'm currently also investigating in using the plugin for provisioning as well. There are additional requirements that come from this use case like the one in #69. Also if this is not the tool for the job I would like to know if there are others that are a better fit. There are concepts like server overlays and tools like the ones in wildfly/wildfly-build-tools but theres hardly any documentation on these or their intended usage.

**Comment by jamezp** [comment]
There is no provisioning tool at this point. I really don't think this plugin should become said tool either. This should work to an extent, but it won't likely ever be a full provisioning tool.

**Comment by ssaarinen** [comment]
I would still give this feature +1 even if provision is out of the plugins scope. I have another use case where I need to perform some configuration to Wildfly prior running Arquillian integration tests. With current state I have to

- reserve a port for wildfly management interface (build-helper-maven-plugin)
- start the server (wf-m-p)
- execute the commands (wf-m-p)
- stop the server (wf-m-p)

This adds a bit too much noise to my poms that I would like to avoid.

With offline support I could see this reducing to 
- execute the commands

which is what I actually want to do.

**Comment by jamezp** [comment]
In some ways I'd hesitate to consider it offline support. The management server still boots so it requires port 9990 by default.

As far as setting up the container before WildFly boots these can all be accomplished currently without having to start  the server. The default configuration uses `${jboss.bind.address:127.0.0.1}` for the address and `${jboss.http.port:8080}` for the port. You could just override the system properties in your `arquillian.xml` file without having to configure anything.

**Comment by jamezp** [comment]
I'd prefer not to support offline CLI from the maven plugin. The server can be started and CLI commands ran against the running container. If only the administration is needed the `--admin-only` flag can be used in the `<server-args/>` (`-Dwildfly.serverArgs="--admin-only"` via the command line).

For the arquillian use case the `@org.jboss.as.arquillian.api.ServerSetup` annotation with a  `org.jboss.as.arquillian.api.ServerSetupTask` can be used to configure the container.
