### ISSUE TITLE
Allow classifiers for deploy-artifact and undeploy-artifact

### ISSUE THREAD

**Issue by shillner** [wildfly/wildfly-maven-plugin#73]
The goals deploy-artifact and undeploy-artifact are not aware of artifact classifiers. Imagine the following constellation:

**Project A:**
* packaging: war
* attaches the classes as a jar with classifier classes

**Project B:**
* has a compile dependency to a-classes.jar
* needs to deploy the artifact a.war in the integration test phase

**Problem:**
Since the compile dependency to the classes jar has been specified first, the plugin will deploy the classes jar instead of the war which breaks the integration tests.

I will send a pull request for this fix.

**Comment by jamezp** [comment]
I've moved this issue to JIRA https://issues.jboss.org/browse/WFMP-20
