### ISSUE TITLE
username and password properties not recognized for deployment

### ISSUE THREAD

**Issue by arun-gupta** [wildfly/wildfly-maven-plugin#78]
Trying to deploy an application to WildFly running as Docker container as:

```
mvn install -Pwildfly -Dwildfly.hostname=192.168.99.100 -Dusername=admin -Dpassword=Admin#007
```

The deployment still prompts for username and password:

```
Nov 26, 2015 5:17:39 AM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 4.0.9.Final
[INFO] Authenticating against security realm: ManagementRealm
Username:admin
Password:
```

**Comment by jamezp** [comment]
It should be `-Dwildfly.username` and `-Dwildfly.password `

**Comment by arun-gupta** [comment]
Thanks!

Blog with usage at: http://blog.arungupta.me/docker-multi-host-networking-couchbase-wildfly/
