### ISSUE TITLE
Add minimum Maven version

### ISSUE THREAD

**Issue by rbellamy** [wildfly/wildfly-maven-plugin#86]
I've just spent a considerable amount of time chasing after a NPE - turns out since you're using `@Inject` this plugin requires Maven 3.1.0+, and IntelliJ IDEA's bundled Maven is at version 3.0.5.

It would still bomb out, but with a clearer error.

I could do a PR if you want. Or you could add:
```xml
<prerequisites>
    <maven>3.1.0</maven> <!-- or something higher -->
</prerequisites>
```
to the plugin [pom.xml](/wildfly-maven-plugin/blob/master/plugin/pom.xml).

**Comment by jamezp** [comment]
Makes sense. I'm only closing as I've moved the issue to JIRA. https://issues.jboss.org/browse/WFMP-25

**Comment by rbellamy** [comment]
Yeah, you know, I noticed you moving things to JIRA - is that where I should go ahead and create issues to start, rather than making you do double-entry?

**Comment by jamezp** [comment]
Yeah. I just don't have the permissions to shut the issues off here :)
