### ISSUE TITLE
Add capability to run web application project in autodeploy/exploded mode

### ISSUE THREAD

**Issue by schrepfler** [wildfly/wildfly-maven-plugin#9]
In order to speed up application development, it's desired to be able to run the web app in exploded mode. Provide the run goal a parameter which will activate this mode, monitor any changes to the project and map that on the target run-time directory (add container specific hooks if needed).

**Comment by bjornbak** [comment]
+1

**Comment by wealima** [comment]
+1

**Comment by jamezp** [comment]
Moved to https://issues.jboss.org/browse/WFMP-2
