### ISSUE TITLE
Option to skip packaging

### ISSUE THREAD

**Issue by ramsrib** [wildfly/wildfly-maven-plugin#93]
Currently when we run wildfly:run, it runs packaging and then starts the application server to deploy the package. If you've multi-module project where ear/war is already built and you just want to deploy that.  In that case, Its a redundant packaging step.

It would be better, if we have some option in maven-wildfly-plugin to **skip** the **packaging** phase for  **wildlfy:run** or **wildfly:deploy** goals.

**Comment by ramsrib** [comment]
In general, I see two ways to use the maven-wildfly-plugin during the development:
1) Start the wildfly server separately and deploy the application using maven-wildfly-plugin
2) Start & deploy using the maven-wildfly-plugin. 

I prefer the second approach, since i don't want to download & manage wildfly separately. In that case, each time i've to build the entire project and then run the 'wildlfly:run' goal to deploy the application. I see a redundancy in the packaging process. Is it possible to avoid this? Or is there a better way to do with the second option? Please correct me, if I'm wrong.

**Comment by jamezp** [comment]
How do you run the goal? From the command line or from an IDE?

In general though you could just `cd ear && mvn wildfly:run`. Yes it would rebuild the EAR, but that's probably not a huge deal.

**Comment by ramsrib** [comment]
I usually run from the command-line as you mentioned. Yeah, May not be a huge deal. but its good to have such option, so that we can save few minutes (since its a big enterprise project) in the deployment.

**Comment by jamezp** [comment]
I really think the `run` goal really needs to fork the `package` lifecycle. Otherwise as a user the `package` phase would have to be explicitly run each time.
