### ISSUE TITLE
Cannot deploy multiple

### ISSUE THREAD

**Issue by Ruudieboy** [wildfly/wildfly-maven-plugin#97]
Im trying to deploy two files from a single pom.xml. I expected that putting in the configuration for each execution would work, but apparently I cannot specify a configuration for an individual execution. The config is not pickup up, it only works when putting the <configuration> outside the <executions> tag. That way I cannot specify multiple files. Any ideas?

 ```
<plugin>
    <groupId>org.wildfly.plugins</groupId>
    <artifactId>wildfly-maven-plugin</artifactId>
    <version>1.1.0.Alpha7</version>
    <executions>
        <execution>
            <id>deploy config</id>
            <phase>install</phase>
            <goals>
                <goal>deploy</goal>
            </goals>
            <configuration>
                <hostname>192.168.99.100</hostname>
                <port>9990</port>
                <name>config</name>
                <filename>config.jar</filename>
            </configuration>
        </execution>
        <execution>
            <id>deploy .ear</id>
            <goals>
                <goal>deploy</goal>
            </goals>
            <configuration>
                <hostname>192.168.99.100</hostname>
                <port>9990</port>
                <name>build.ear</name>
                <filename>build.ear</filename>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Results in:
`java.net.ConnectException: WFLYPRT0053: Could not connect to http-remoting://localhost:9990. The connection failed: Connection refused`

**Comment by jamezp** [comment]
Are you trying to execute a specific `wildfly:goal` from the command line? If that's the case then maven doesn't not use executions for those explicit goal invocations. Executions are meant to bind to a maven lifecyle phase.

**Comment by Ruudieboy** [comment]
Ah yes of course. I was trying to run wildfly:deploy and make it deploy both the config.jar and the build.ear. I guess that's not possible? I could make use of a profile and run the command twice.
`mvn wildfly:deploy -P wildfly-config`
`mvn wildfly:deploy -P wildfly-build`

**Comment by jamezp** [comment]
Yeah. You could use a single profile or bind each execution to a specific goal. So something like the following should work. Anytime you run `mvn install` both would be deployments would be deployed.
```xml
<plugin>
    <groupId>org.wildfly.plugins</groupId>
    <artifactId>wildfly-maven-plugin</artifactId>
    <version>1.1.0.Alpha7</version>
    <configuration>
        <hostname>192.168.99.100</hostname>
        <port>9990</port>
    </configuration>
    <executions>
        <execution>
            <id>deploy config</id>
            <phase>install</phase>
            <goals>
                <goal>deploy</goal>
            </goals>
            <configuration>
                <name>config</name>
                <filename>config.jar</filename>
            </configuration>
        </execution>
        <execution>
            <id>deploy.ear</id>
            <phase>install</phase>
            <goals>
                <goal>deploy</goal>
            </goals>
            <configuration>
                <name>build.ear</name>
                <filename>build.ear</filename>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by Ruudieboy** [comment]
Awesome, thanks for your help!
